In [8]:
cursor.execute('''DROP TABLE poverty_rate_by_state_2023''')
cursor.execute('''DROP TABLE us_state_vaccinations''')
cursor.execute('''DROP TABLE race_breakdown''')
cursor.execute('''DROP TABLE sagdp1__all_areas_1997_2022''')

OperationalError: no such table: poverty_rate_by_state_2023

In [9]:
import sqlite3
import csv


conn = sqlite3.connect('database.db')


cursor = conn.cursor()


cursor.execute('''CREATE TABLE poverty_rate_by_state_2023 (
                    state VARCHAR,
                    PovertyRate FLOAT,
                    undefined INTEGER,
                    FOREIGN KEY (state) REFERENCES race_breakdown(State)
                )''')


cursor.execute('''CREATE TABLE us_state_vaccinations (
                    date VARCHAR,
                    location VARCHAR,
                    total_vaccinations INTEGER,
                    total_distributed INTEGER,
                    people_vaccinated INTEGER,
                    people_fully_vaccinated_per_hundred FLOAT,
                    total_vaccinations_per_hundred FLOAT,
                    people_fully_vaccinated INTEGER,
                    people_vaccinated_per_hundred FLOAT,
                    distributed_per_hundred FLOAT,
                    daily_vaccinations_raw INTEGER,
                    daily_vaccinations INTEGER,
                    daily_vaccinations_per_million INTEGER,
                    share_doses_used FLOAT,
                    total_boosters INTEGER,
                    total_boosters_per_hundred FLOAT,
                    FOREIGN KEY (location) REFERENCES race_breakdown(State)
                )''')


cursor.execute('''CREATE TABLE race_breakdown (
                    State VARCHAR PRIMARY KEY,
                    Total INTEGER,
                    Population_of_one_race INTEGER,
                    White_alone INTEGER,
                    Black_or_African_American_alone INTEGER,
                    American_Indian_and_Alaska_Native_alone INTEGER,
                    Asian_alone INTEGER,
                    Native_Hawaiian_and_Other_Pacific_Islander_alone INTEGER,
                    Some_Other_Race_alone INTEGER,
                    Population_of_two_or_more_races INTEGER,
                    Population_of_two_races INTEGER,
                    White__Black_or_African_American INTEGER,
                    White__American_Indian_and_Alaska_Native INTEGER,
                    White__Asian INTEGER,
                    White__Native_Hawaiian_and_Other_Pacific_Islander INTEGER,
                    White__Some_Other_Race INTEGER,
                    Black_or_African_American__American_Indian_and_Alaska_Native INTEGER,
                    Black_or_African_American__Asian INTEGER,
                    Black_or_African_American__Native_Hawaiian_and_Other_Pacific_Islander INTEGER,
                    Black_or_African_American__Some_Other_Race INTEGER,
                    American_Indian_and_Alaska_Native__Asian INTEGER,
                    American_Indian_and_Alaska_Native__Native_Hawaiian_and_Other_Pacific_Islander INTEGER,
                    American_Indian_and_Alaska_Native__Some_Other_Race INTEGER,
                    Asian__Native_Hawaiian_and_Other_Pacific_Islander INTEGER,
                    Asian__Some_Other_Race INTEGER,
                    Native_Hawaiian_and_Other_Pacific_Islander__Some_Other_Race INTEGER
                )''')


cursor.execute('''CREATE TABLE sagdp1__all_areas_1997_2022 (
                    GeoFIPS VARCHAR PRIMARY KEY,
                    GeoName VARCHAR,
                    TableName VARCHAR,
                    Description VARCHAR,
                    Unit VARCHAR,
                    "1997" INTEGER,
                    "1998" INTEGER,
                    "1999" INTEGER,
                    "2000" INTEGER,
                    "2001" INTEGER,
                    "2002" INTEGER,
                    "2003" INTEGER,
                    "2004" INTEGER,
                    "2005" INTEGER,
                    "2006" INTEGER,
                    "2007" INTEGER,
                    "2008" INTEGER,
                    "2009" INTEGER,
                    "2010" INTEGER,
                    "2011" INTEGER,
                    "2012" INTEGER,
                    "2013" INTEGER,
                    "2014" INTEGER,
                    "2015" INTEGER,
                    "2016" INTEGER,
                    "2017" INTEGER,
                    "2018" INTEGER,
                    "2019" INTEGER,
                    "2020" INTEGER,
                    "2021" INTEGER,
                    "2022" INTEGER
                )''')


def import_data_from_csv(table_name):
 
    csv_file_path = f'data/{table_name}.csv'
    
  
    with open(csv_file_path, 'r') as file:
       
        csv_reader = csv.reader(file)
        
     
        next(csv_reader)
        
    
        for row in csv_reader:
            # Prepare the SQL query to insert a row
            query = f"INSERT INTO {table_name} VALUES ({','.join(['?'] * len(row))})"
            
         
            cursor.execute(query, row)

     
        conn.commit()
        print(f"Data imported into the table '{table_name}' successfully.")


tables = ['poverty_rate_by_state_2023', 'us_state_vaccinations', 'race_breakdown', 'sagdp1__all_areas_1997_2022']
for table_name in tables:
    import_data_from_csv(table_name)


conn.close()

Data imported into the table 'poverty_rate_by_state_2023' successfully.
Data imported into the table 'us_state_vaccinations' successfully.
Data imported into the table 'race_breakdown' successfully.
Data imported into the table 'sagdp1__all_areas_1997_2022' successfully.