In [1]:
cursor.execute('''DROP TABLE poverty_rate_by_state_2023''')
cursor.execute('''DROP TABLE us_state_vaccinations''')
cursor.execute('''DROP TABLE race_breakdown''')
cursor.execute('''DROP TABLE sagdp1__all_areas_1997_2022''')

NameError: name 'cursor' is not defined

In [2]:
import sqlite3
import csv


conn = sqlite3.connect('database.db')


cursor = conn.cursor()


cursor.execute('''CREATE TABLE poverty_rate_by_state_2023 (
                    state VARCHAR PRIMARY KEY,
                    PovertyRate FLOAT,
                    undefined INTEGER,
                    FOREIGN KEY (state) REFERENCES race_breakdown(State)
                )''')

cursor.execute('''CREATE TABLE us_state_vaccinations (
                    id INTEGER PRIMARY KEY,
                    date VARCHAR,
                    location VARCHAR,
                    total_vaccinations INTEGER,
                    total_distributed INTEGER,
                    people_vaccinated INTEGER,
                    people_fully_vaccinated_per_hundred FLOAT,
                    total_vaccinations_per_hundred FLOAT,
                    people_fully_vaccinated INTEGER,
                    people_vaccinated_per_hundred FLOAT,
                    distributed_per_hundred FLOAT,
                    daily_vaccinations_raw INTEGER,
                    daily_vaccinations INTEGER,
                    daily_vaccinations_per_million INTEGER,
                    share_doses_used FLOAT,
                    total_boosters INTEGER,
                    total_boosters_per_hundred FLOAT,
                    FOREIGN KEY (location) REFERENCES race_breakdown(State)
                )''')


cursor.execute('''CREATE TABLE race_breakdown (
                    State VARCHAR PRIMARY KEY,
                    Total INTEGER,
                    Population_of_one_race INTEGER,
                    White_alone INTEGER,
                    Black_or_African_American_alone INTEGER,
                    American_Indian_and_Alaska_Native_alone INTEGER,
                    Asian_alone INTEGER,
                    Native_Hawaiian_and_Other_Pacific_Islander_alone INTEGER,
                    Some_Other_Race_alone INTEGER,
                    Population_of_two_or_more_races INTEGER,
                    Population_of_two_races INTEGER,
                    White__Black_or_African_American INTEGER,
                    White__American_Indian_and_Alaska_Native INTEGER,
                    White__Asian INTEGER,
                    White__Native_Hawaiian_and_Other_Pacific_Islander INTEGER,
                    White__Some_Other_Race INTEGER,
                    Black_or_African_American__American_Indian_and_Alaska_Native INTEGER,
                    Black_or_African_American__Asian INTEGER,
                    Black_or_African_American__Native_Hawaiian_and_Other_Pacific_Islander INTEGER,
                    Black_or_African_American__Some_Other_Race INTEGER,
                    American_Indian_and_Alaska_Native__Asian INTEGER,
                    American_Indian_and_Alaska_Native__Native_Hawaiian_and_Other_Pacific_Islander INTEGER,
                    American_Indian_and_Alaska_Native__Some_Other_Race INTEGER,
                    Asian__Native_Hawaiian_and_Other_Pacific_Islander INTEGER,
                    Asian__Some_Other_Race INTEGER,
                    Native_Hawaiian_and_Other_Pacific_Islander__Some_Other_Race INTEGER
                )''')


cursor.execute('''CREATE TABLE sagdp1__all_areas_1997_2022 (
                    GeoFIPS VARCHAR PRIMARY KEY,
                    GeoName VARCHAR,
                    TableName VARCHAR,
                    Description VARCHAR,
                    Unit VARCHAR,
                    "Y1997" INTEGER,
                    "Y1998" INTEGER,
                    "Y1999" INTEGER,
                    "Y2000" INTEGER,
                    "Y2001" INTEGER,
                    "Y2002" INTEGER,
                    "Y2003" INTEGER,
                    "Y2004" INTEGER,
                    "Y2005" INTEGER,
                    "Y2006" INTEGER,
                    "Y2007" INTEGER,
                    "Y2008" INTEGER,
                    "Y2009" INTEGER,
                    "Y2010" INTEGER,
                    "Y2011" INTEGER,
                    "Y2012" INTEGER,
                    "Y2013" INTEGER,
                    "Y2014" INTEGER,
                    "Y2015" INTEGER,
                    "Y2016" INTEGER,
                    "Y2017" INTEGER,
                    "Y2018" INTEGER,
                    "Y2019" INTEGER,
                    "Y2020" INTEGER,
                    "Y2021" INTEGER,
                    "Y2022" INTEGER
                )''')

cursor.execute('''CREATE TABLE cleaned_voting (
                    State VARCHAR PRIMARY KEY,
                    Candidate_1 VARCHAR,
                    Candidate_1_Party VARCHAR,
                    Candidate_1_Votes INTEGER,
                    Candidate_2 VARCHAR,
                    Candidate_2_Party VARCHAR,
                    Candidate_2_Votes INTEGER,
                    Winning_Party VARCHAR,
                    Total_Votes INTEGER,
                    FOREIGN KEY (State) REFERENCES race_breakdown(State)
                )''')


def import_data_from_csv(table_name):
 
    csv_file_path = f'data/{table_name}.csv'
    
  
    with open(csv_file_path, 'r') as file:
       
        csv_reader = csv.reader(file)
        
     
        next(csv_reader)
        
    
        for row in csv_reader:
            # Prepare the SQL query to insert a row
            query = f"INSERT INTO {table_name} VALUES ({','.join(['?'] * len(row))})"
            
         
            cursor.execute(query, row)

     
        conn.commit()
        print(f"Data imported into the table '{table_name}' successfully.")


tables = ['poverty_rate_by_state_2023', 'us_state_vaccinations', 'race_breakdown', 'sagdp1__all_areas_1997_2022','cleaned_voting']
for table_name in tables:
    import_data_from_csv(table_name)


conn.close()

OperationalError: table poverty_rate_by_state_2023 already exists